const FaceRecognitionActionTypes = {
  DETECT_FACES_START: 'DETECT_FACES_START',
  DETECT_FACES_SUCCESS: 'DETECT_FACES_SUCCESS',
  DETECT_FACES_FAILURE: 'DETECT_FACES_FAILURE',
  RESET_FACE_BOXES: 'RESET_FACE_BOXES',
  ADD_DETECTED_URL: 'ADD_DETECTED_URL',
  SET_IMAGE_URL: 'SET_IMAGE_URL',
  RESET_FACE_RECOGNITION: 'RESET_FACE_RECOGNITION',
};

export default FaceRecognitionActionTypes;
