const UserActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT: 'SIGN_OUT',
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  UPDATE_ENTRIES_SUCCESS: 'UPDATE_ENTRIES_SUCCESS',
  UPDATE_ENTRIES_FAILURE: 'UPDATE_ENTRIES_FAILURE',
};

export default UserActionTypes;
